name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build & Push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: beming/${{ github.event.repository.name }}:${{ github.sha }}

    - name: Checkout infra repo
      uses: actions/checkout@v3
      with:
        repository: beming-dev/stock-simulator-cicd
        token: ${{ secrets.INFRA_TOKEN }}
        path: infra
        persist-credentials: true

    - name: Update Kustomize image tag
      run: |
        cd infra/base
        yq e '.images[] 
          |= select(.name=="beming/'${{ github.repository }}'") 
          .newTag = "'${{ github.sha }}'"' -i kustomization.yaml

    - name: Commit & Push infra changes
      run: |
        cd infra
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        git add .
        git commit -m "chore: bump ${{ github.repository }} to ${{ github.sha }}"
        git push